### ISSUE TITLE
boltdb related crashes

### ISSUE THREAD

**Issue by NickTitle** [kolide/launcher#313]
- launcher had been long-running and i noticed a crash this morning
- i slept my computer and came back, but that does not seem to be the cause

snip
```
unexpected fault address 0x7404050
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7404050 pc=0x405be6f]

goroutine 29 [running]:
runtime.throw(0x4644312, 0x5)
	/usr/local/go/src/runtime/panic.go:619 +0x81 fp=0xc420325968 sp=0xc420325948 pc=0x402d851
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:395 +0x211 fp=0xc4203259b8 sp=0xc420325968 pc=0x4043531
runtime.cmpbody()
	/usr/local/go/src/runtime/asm_amd64.s:1590 +0xaf fp=0xc4203259c0 sp=0xc4203259b8 pc=0x405be6f
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*Cursor).searchPage.func1(0xd, 0x0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/cursor.go:302 +0x96 fp=0xc420325a10 sp=0xc4203259c0 pc=0x42fe686
sort.Search(0x1b, 0xc420325a88, 0x42f00ce)
	/usr/local/go/src/sort/search.go:66 +0x58 fp=0xc420325a48 sp=0xc420325a10 pc=0x40b6158
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*Cursor).searchPage(0xc420325c38, 0x7404050, 0x8, 0x8, 0x8740000)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/cursor.go:299 +0xd1 fp=0xc420325ad8 sp=0xc420325a48 pc=0x42f1a61
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc420325c38, 0x7404050, 0x8, 0x8, 0x740)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/cursor.go:271 +0x18b fp=0xc420325b90 sp=0xc420325ad8 pc=0x42f162b
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*Cursor).seek(0xc420325c38, 0x7404050, 0x8, 0x8, 0x0, 0x0, 0x1, 0x1, 0xc420325c58, 0x42fb17f, ...)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/cursor.go:159 +0xa5 fp=0xc420325be0 sp=0xc420325b90 pc=0x42f0df5
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*Bucket).Delete(0xc4200aed40, 0x7404050, 0x8, 0x8, 0xc4200aed40, 0x20)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/bucket.go:326 +0xcc fp=0xc420325c68 sp=0xc420325be0 pc=0x42ee3bc
github.com/kolide/launcher/osquery.(*Extension).writeBufferedLogsForType.func2(0xc4202bce00, 0x466d140, 0xc4202bce00)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/extension.go:493 +0xc8 fp=0xc420325cf0 sp=0xc420325c68 pc=0x444e1b8
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4201fa000, 0xc420325dd0, 0x0, 0x0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/db.go:598 +0x90 fp=0xc420325d40 sp=0xc420325cf0 pc=0x42f3da0
github.com/kolide/launcher/osquery.(*Extension).writeBufferedLogsForType(0xc4201f0160, 0x4, 0xc4207c0f60, 0x2)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/extension.go:490 +0x1f5 fp=0xc420325e30 sp=0xc420325d40 pc=0x444b9c5
github.com/kolide/launcher/osquery.(*Extension).writeAndPurgeLogs(0xc4201f0160)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/extension.go:402 +0x77 fp=0xc420325f08 sp=0xc420325e30 pc=0x444b1f7
github.com/kolide/launcher/osquery.(*Extension).writeLogsLoopRunner(0xc4201f0160)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/extension.go:426 +0xd1 fp=0xc420325fd8 sp=0xc420325f08 pc=0x444b6b1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420325fe0 sp=0xc420325fd8 pc=0x405c6d1
created by github.com/kolide/launcher/osquery.(*Extension).Start
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/extension.go:158 +0x5f

goroutine 1 [chan receive, 184 minutes]:
main.main()
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/cmd/launcher/launcher.go:416 +0x1034

goroutine 19 [syscall, 184 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa7
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 22 [chan receive, 184 minutes]:
github.com/kolide/launcher/debug.AttachLogToggle.func1(0xc420128420, 0xc4200ac777, 0xc420186b60)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/debug/debug.go:36 +0x43
created by github.com/kolide/launcher/debug.AttachLogToggle
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/debug/debug.go:34 +0xe0

goroutine 21 [select, 184 minutes, locked to thread]:
runtime.gopark(0x466e7d0, 0x0, 0x4645732, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc4201c6750, 0xc42008c1e0)
	/usr/local/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:549 +0x1c6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 4 [chan receive, 184 minutes]:
github.com/kolide/launcher/debug.AttachDebugHandler.func1(0xc420128480, 0xc4200b44a0, 0x1b, 0x46b13c0, 0xc420186b60)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/debug/debug.go:56 +0x3e
created by github.com/kolide/launcher/debug.AttachDebugHandler
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/debug/debug.go:53 +0xd3

goroutine 6 [select, 184 minutes]:
github.com/kolide/launcher/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc42019c630)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:109 +0x182
created by github.com/kolide/launcher/vendor/google.golang.org/grpc.(*ccResolverWrapper).start
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:95 +0x3f

goroutine 50 [select, 184 minutes]:
github.com/kolide/launcher/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc42022a0c0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x14a
created by github.com/kolide/launcher/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x14f

goroutine 51 [select, 184 minutes]:
github.com/kolide/launcher/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc420236000)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/clientconn.go:1373 +0x23b
github.com/kolide/launcher/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc420236000)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/clientconn.go:949 +0x1b5
created by github.com/kolide/launcher/vendor/google.golang.org/grpc.(*addrConn).connect
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/clientconn.go:940 +0xe1

goroutine 35 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x68e6c30, 0x72, 0xc4202a2bb8)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42024a118, 0x72, 0xffffffffffffff00, 0x46b3160, 0x495e710)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42024a118, 0xc420260000, 0x8000, 0x8000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42024a100, 0xc420260000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x1dc
net.(*netFD).Read(0xc42024a100, 0xc420260000, 0x8000, 0x8000, 0x11, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4201a6048, 0xc420260000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
bufio.(*Reader).Read(0xc4201b0180, 0xc420278038, 0x9, 0x9, 0x20, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x46b0fa0, 0xc4201b0180, 0xc420278038, 0x9, 0x9, 0x9, 0xc4202a2df0, 0x400301e, 0xc4202a2e9f)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x46b0fa0, 0xc4201b0180, 0xc420278038, 0x9, 0x9, 0x43a3d7d, 0xc4202ba28c, 0xc4203fc000)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/kolide/launcher/vendor/golang.org/x/net/http2.readFrameHeader(0xc420278038, 0x9, 0x9, 0x46b0fa0, 0xc4201b0180, 0x0, 0xbec6c62e00000000, 0x9e0a9032855, 0x49ab160)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/kolide/launcher/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc420278000, 0xc4202ba280, 0xc4202ba280, 0x0, 0x0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/kolide/launcher/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc42027a000)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/transport/http2_client.go:1123 +0x115
created by github.com/kolide/launcher/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/transport/http2_client.go:265 +0xb3f

goroutine 36 [select, 4 minutes]:
github.com/kolide/launcher/vendor/google.golang.org/grpc/transport.(*controlBuffer).get(0xc42019e100, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/transport/controlbuf.go:289 +0x133
github.com/kolide/launcher/vendor/google.golang.org/grpc/transport.(*loopyWriter).run(0xc420230660)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/transport/controlbuf.go:374 +0x1bc
github.com/kolide/launcher/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc42027a000)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/transport/http2_client.go:298 +0x7c
created by github.com/kolide/launcher/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/google.golang.org/grpc/transport/http2_client.go:296 +0xc8f

goroutine 55779 [syscall, 44 minutes]:
syscall.Syscall6(0x7, 0x5cee, 0xc4205cd61c, 0x0, 0xc4201d4120, 0x0, 0x0, 0x90, 0xc4201d4120, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:41 +0x5
syscall.wait4(0x5cee, 0xc4205cd61c, 0x0, 0xc4201d4120, 0x90, 0x462d880, 0xc4205cd601)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:34 +0x7e
syscall.Wait4(0x5cee, 0xc4205cd66c, 0x0, 0xc4201d4120, 0x44189d9, 0x458fb20, 0x46ba4a0)
	/usr/local/go/src/syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc420022660, 0xc420186de0, 0x46bdba0, 0xc42066a120)
	/usr/local/go/src/os/exec_unix.go:38 +0x7e
os.(*Process).Wait(0xc420022660, 0x0, 0xc420082e98, 0xc4201c1200)
	/usr/local/go/src/os/exec.go:123 +0x2b
os/exec.(*Cmd).Wait(0xc42095c2c0, 0x402c369, 0xc400000008)
	/usr/local/go/src/os/exec/exec.go:461 +0x5c
github.com/kolide/launcher/osquery/runtime.(*Runner).launchOsqueryInstance.func5(0x8, 0x466e928)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/runtime/runtime.go:478 +0x35
github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420338440, 0xc4201a4320)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66

goroutine 28 [chan receive, 44 minutes]:
github.com/kolide/launcher/osquery/runtime.(*Runner).start.func1(0xc42019ca50)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/runtime/runtime.go:358 +0x7c
created by github.com/kolide/launcher/osquery/runtime.(*Runner).start
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/runtime/runtime.go:352 +0xa1

goroutine 55599 [select, 1 minutes]:
github.com/kolide/launcher/osquery/runtime.(*Runner).launchOsqueryInstance.func9(0x0, 0x0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/runtime/runtime.go:567 +0x141
github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420338440, 0xc4202206d0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66

goroutine 55780 [chan receive, 44 minutes]:
github.com/kolide/launcher/osquery/runtime.(*Runner).launchOsqueryInstance.func6(0xc400000008, 0x466e928)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/runtime/runtime.go:486 +0x59
github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420338440, 0xc4201a4330)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66

goroutine 55597 [IO wait]:
internal/poll.runtime_pollWait(0x68e65b0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420668798, 0x72, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420668798, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420668780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc420668780, 0x4013918, 0x30, 0x45c9600)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*UnixListener).accept(0xc42019de90, 0x45c9600, 0xc42066db30, 0xc420186e20)
	/usr/local/go/src/net/unixsock_posix.go:162 +0x32
net.(*UnixListener).Accept(0xc42019de90, 0x4036d14, 0xc4206e1e40, 0x4058f40, 0xc4206e1e80)
	/usr/local/go/src/net/unixsock.go:253 +0x49
github.com/kolide/launcher/vendor/git.apache.org/thrift.git/lib/go/thrift.(*TServerSocket).Accept(0xc4207c2b40, 0x466d128, 0xc420668700, 0x46ba500, 0xc42066db30)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/git.apache.org/thrift.git/lib/go/thrift/server_socket.go:83 +0x81
github.com/kolide/launcher/vendor/git.apache.org/thrift.git/lib/go/thrift.(*TSimpleServer).AcceptLoop(0xc420668700, 0x0, 0x0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/git.apache.org/thrift.git/lib/go/thrift/simple_server.go:130 +0x48
github.com/kolide/launcher/vendor/git.apache.org/thrift.git/lib/go/thrift.(*TSimpleServer).Serve(0xc420668700, 0xc4206e1f20, 0x0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/git.apache.org/thrift.git/lib/go/thrift/simple_server.go:156 +0x5c
github.com/kolide/launcher/vendor/github.com/kolide/osquery-go.(*ExtensionManagerServer).Start(0xc4201f2460, 0xc4205cbf78, 0x402c369)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/github.com/kolide/osquery-go/server.go:168 +0x78
github.com/kolide/launcher/osquery/runtime.(*Runner).launchOsqueryInstance.func7(0xc400000008, 0x466e928)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/runtime/runtime.go:544 +0x4c
github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420338440, 0xc4202206b0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66

goroutine 55600 [chan receive, 44 minutes]:
github.com/kolide/launcher/osquery/runtime.(*Runner).launchOsqueryInstance.func10(0xc400000008, 0x466e928)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/runtime/runtime.go:580 +0x59
github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420338440, 0xc4202206e0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66

goroutine 55778 [IO wait]:
internal/poll.runtime_pollWait(0x68e6dd0, 0x72, 0xc4202a3d58)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4207c24c8, 0x72, 0xffffffffffffff01, 0x46b3160, 0x495e710)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4207c24c8, 0xc420cd8001, 0x8000, 0x8000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4207c24b0, 0xc420cd8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x1dc
os.(*File).read(0xc4201a6098, 0xc420cd8000, 0x8000, 0x8000, 0x0, 0x7137, 0xc4206d2000)
	/usr/local/go/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc4201a6098, 0xc420cd8000, 0x8000, 0x8000, 0x7138, 0x0, 0x0)
	/usr/local/go/src/os/file.go:107 +0x6a
io.copyBuffer(0x46b13e0, 0xc4200584e0, 0x46b20a0, 0xc4201a6098, 0xc420cd8000, 0x8000, 0x8000, 0x403fe04, 0xc420776a94, 0xc4205c6700)
	/usr/local/go/src/io/io.go:400 +0x164
io.Copy(0x46b13e0, 0xc4200584e0, 0x46b20a0, 0xc4201a6098, 0x4072444, 0xc420776a88, 0xffffffffffffffff)
	/usr/local/go/src/io/io.go:362 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0x4485380, 0x46b1780)
	/usr/local/go/src/os/exec/exec.go:275 +0x4d
os/exec.(*Cmd).Start.func1(0xc42095c2c0, 0xc420d0e440)
	/usr/local/go/src/os/exec/exec.go:396 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:395 +0x5df

goroutine 55598 [chan receive, 44 minutes]:
github.com/kolide/launcher/osquery/runtime.(*Runner).launchOsqueryInstance.func8(0x8, 0x466e928)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/osquery/runtime/runtime.go:552 +0x59
github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420338440, 0xc4202206c0)
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/Users/nicholasesposito/go/src/github.com/kolide/launcher/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

**Comment by marpaia** [comment]
We've seen this crash caused by Bolt before.. perhaps it's time to add a top-level `recover`?

**Comment by zwass** [comment]
I don't think we should attempt any recovery from a segfault like this. Rather, let's let the thing crash and be brought back up by the init system.

If anyone is ever able to repro this (or we start seeing it more often), I'd love to dig more deeply into what the crash is about. Otherwise it's so deep in the Bolt code it doesn't seem very worthwhile to pursue.

**Comment by zwass** [comment]
I had always read https://github.com/boltdb/bolt#project-status (and the section below it) to indicate that this was likely to be the most stable version of Bolt. Just now I took a look at the commits in the new fork and it seems there are a variety of bugfixes. It may be worth trying to swap it in at some point and see whether we achieve better stability.

**Comment by zwass** [comment]
Adding some other BoltDB related crashes we've experienced:

```
goroutine 1 [running]:
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc420717790, 0xc4201fc120, 0x6, 0x8, 0x1468d)
/Users/wstewart/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/cursor.go:256 +0x388
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*Cursor).seek(0xc420063790, 0xc4201fc120, 0x6, 0x8, 0x0, 0x0, 0x40d92e9, 0x46d5e60, 0xc42038a120, 0x0, ...)
/Users/wstewart/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/cursor.go:159 +0xa5
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*Bucket).CreateBucket(0xc4201da2b8, 0xc4201fc120, 0x6, 0x8, 0xc4201fc126, 0x2, 0x0)
/Users/wstewart/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/bucket.go:172 +0xfa
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*Bucket).CreateBucketIfNotExists(0xc4201da2b8, 0xc4201fc120, 0x6, 0x8, 0x6, 0x8, 0xc4201fc120)
/Users/wstewart/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/bucket.go:206 +0x4d
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*Tx).CreateBucketIfNotExists(0xc4201da2a0, 0xc4201fc120, 0x6, 0x8, 0x6, 0x8, 0xc400000008)
/Users/wstewart/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/tx.go:115 +0x4f
github.com/kolide/launcher/pkg/osquery.NewExtension.func1(0xc4201da2a0, 0x468a0d0, 0xc4201da2a0)
/Users/wstewart/go/src/github.com/kolide/launcher/pkg/osquery/extension.go:134 +0xa2
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4201f0000, 0xc420717998, 0x0, 0x0)
/Users/wstewart/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/db.go:598 +0x90
github.com/kolide/launcher/pkg/osquery.NewExtension(0x46d85a0, 0xc4201f6480, 0xc4201f0000, 0xc420708000, 0x1e0, 0x200000, 0xdf8475800, 0x46d8d80, 0x49f7340, 0x46cf400, ...)
/Users/wstewart/go/src/github.com/kolide/launcher/pkg/osquery/extension.go:132 +0x11d
main.createExtensionRuntime(0x46d64e0, 0xc4201f4080, 0xc42002601f, 0x2a, 0xc4201f0000, 0x46cf400, 0xc4201b2500, 0xc4201da000, 0x40129f9, 0x32, ...)
/Users/wstewart/go/src/github.com/kolide/launcher/cmd/launcher/extension.go:74 +0x275
main.main()
/Users/wstewart/go/src/github.com/kolide/launcher/cmd/launcher/main.go:284 +0x454
```

```
goroutine 1 [running]:
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*freelist).free(0xc420194450, 0x4e4777, 0x5a0b000)
/Users/wstewart/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/freelist.go:121 +0x2eb
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc4202222a0, 0x0, 0x0)
/Users/wstewart/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/tx.go:176 +0x1dc
github.com/kolide/launcher/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4201f0000, 0xc42023b998, 0x0, 0x0)
/Users/wstewart/go/src/github.com/kolide/launcher/vendor/github.com/boltdb/bolt/db.go:605 +0xe8
github.com/kolide/launcher/pkg/osquery.NewExtension(0x46d85a0, 0xc420198520, 0xc4201f0000, 0xc42021c000, 0x1e2, 0x200000, 0xdf8475800, 0x46d8d80, 0x49f7340, 0x46cf400, ...)
/Users/wstewart/go/src/github.com/kolide/launcher/pkg/osquery/extension.go:132 +0x11d
main.createExtensionRuntime(0x46d64e0, 0xc4201c8100, 0xc42002601f, 0x2b, 0xc4201f0000, 0x46cf400, 0xc4201b4560, 0xc4201ea000, 0x40129f9, 0x32, ...)
/Users/wstewart/go/src/github.com/kolide/launcher/cmd/launcher/extension.go:74 +0x275
main.main()
/Users/wstewart/go/src/github.com/kolide/launcher/cmd/launcher/main.go:284 +0x454
{"caller":"client.go:114","cert_pinning":false,"component":"launcher","grpc_secure":true,"level":"info","msg":"dialing grpc server","server":"dichuja.launcher.kolide.com:443","tls_secure":true,"ts":"2018-09-25T12:38:06.298611235Z"}
panic: page 15 already freed
```

**Comment by directionless** [comment]
Haven't seen indication of this in awhile, and I have a PR up to swap to bbolt.
