### ISSUE TITLE
package-builder fails when building for debs 

### ISSUE THREAD

**Issue by antoinette0x53** [kolide/launcher#533]
This issue is happening to me on a fresh install of launcher. 
launcher - version 0.11.2-dirty
  branch: 	master
  revision: 	`2878f9e2cc3102c4fc341a110ade9a4d240f1c7d`
  build date: 	2019-10-25
  build user: 	
  go version: 	go1.13.3

```
$ ./build/package-builder make --hostname=test.com:443 -targets="linux-systemd-deb" -package_version="stable" -debug
{"caller":"level.go:63","level":"debug","msg":"starting download","span_id":"2afaac885be1d705","trace_id":"beb696994b5030782093b47f6d0e06e4","trace_is_sampled":false,"ts":"2019-10-25T15:56:44.797538Z","url":"https://dl.kolide.co/kolide/osqueryd/linux/osqueryd-stable.tar.gz"}
{"caller":"level.go:63","level":"debug","msg":"starting download","span_id":"0c3df2e747ac32f6","trace_id":"2ce62853b9a27133522f15bd7c03bbad","trace_is_sampled":false,"ts":"2019-10-25T15:56:46.683304Z","url":"https://dl.kolide.co/kolide/launcher/linux/launcher-stable.tar.gz"}
{"caller":"level.go:63","level":"debug","msg":"starting download","span_id":"ee7f374734778de6","trace_id":"4a5611638e7079656d070a55121d38af","trace_is_sampled":false,"ts":"2019-10-25T15:56:47.415932Z","url":"https://dl.kolide.co/kolide/osquery-extension/linux/osquery-extension-stable.tar.gz"}
could not generate packages: making package: packaging, target linux-systemd-deb: creating fpm package: /usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:430:in `read': No such file or directory @ rb_sysopen - /pkgscripts/postinstall (Errno::ENOENT)
	from /usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:430:in `block in execute'
	from /usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:434:in `execute'
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:560:in `run'
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /usr/local/bundle/gems/fpm-1.8.1/bin/fpm:8:in `<top (required)>'
	from /usr/local/bundle/bin/fpm:22:in `load'
	from /usr/local/bundle/bin/fpm:22:in `<main>'
: exit status 1
```

**Comment by directionless** [comment]
package-builder generally builds the debs via a docker container, running from macos.

What kind of environment are you running that on?

Why do you have a dirty checkout?

**Comment by antoinette0x53** [comment]
I'm running on macos
```
System Version: macOS 10.14.5 (18F203)
      Kernel Version: Darwin 18.6.0
```

I did a git clone on the launcher repo and then ran 
```make launcher
make deps
```
based on what I found here https://github.com/kolide/launcher/blob/master/docs/launcher.md

**Comment by directionless** [comment]
It may be a red-herring. package-builder is separate from launcher. You do not need to build launcher to package it, and by default package-builder downloads from kolide's published binaries. https://github.com/kolide/launcher/blob/master/docs/package-builder.md are the instructions for using it.

The error you're getting is coming straight out of docker, and fpm. It makes me wonder if there's an issue with the docker mounts.

**Comment by antoinette0x53** [comment]
I blew away the docker machine and created another one and re-ran the command for kolide/fpm
```
$ docker run --rm -it kolide/fpm echo "it works"
Unable to find image 'kolide/fpm:latest' locally
latest: Pulling from kolide/fpm
6d827a3ef358: Pull complete 
2726297beaf1: Pull complete 
7d27bd3d7fec: Pull complete 
44ae682c18a3: Pull complete 
59c43fd2bed9: Pull complete 
bb4fe7bb11cc: Pull complete 
033e9c499340: Pull complete 
1cf3484dfbb6: Pull complete 
eb8f339407e0: Pull complete 
1b87eba86e4e: Pull complete 
bb67d5ede4be: Pull complete 
bafa4df0eda6: Pull complete 
Digest: sha256:746c4920c35425d66bd13d4fddadf73b31cd65446584b22e2b65260b2f5b432f
Status: Downloaded newer image for kolide/fpm:latest
it works
```

I still got the same error

**Comment by directionless** [comment]
I've just added some additional debugging to that. Can you update to the latest code, rebuild package-builder and try again? Let's see what the logging there surfaces

**Comment by antoinette0x53** [comment]
You were right about the mounts

```
./build/package-builder make --hostname=test.com:443 -targets="linux-systemd-deb" -package_version="stable" -debug
{"caller":"level.go:63","level":"debug","msg":"starting download","span_id":"a28798ff0dc2e558","trace_id":"aa498d87db922560f3a55ea1cbee48f2","trace_is_sampled":false,"ts":"2019-10-25T17:07:44.98384Z","url":"https://dl.kolide.co/kolide/osqueryd/linux/osqueryd-stable.tar.gz"}
{"caller":"level.go:63","level":"debug","msg":"starting download","span_id":"04e26ef18620c96d","trace_id":"5cf36cb1007633208787c2bfd5843ad3","trace_is_sampled":false,"ts":"2019-10-25T17:07:46.932005Z","url":"https://dl.kolide.co/kolide/launcher/linux/launcher-stable.tar.gz"}
{"caller":"level.go:63","level":"debug","msg":"starting download","span_id":"663c45e3ff7eac82","trace_id":"725a957da480c423e417020a5d26384a","trace_is_sampled":false,"ts":"2019-10-25T17:07:47.599656Z","url":"https://dl.kolide.co/kolide/osquery-extension/linux/osquery-extension-stable.tar.gz"}
{"caller":"packagekit.PackageFPM","cmd":"docker run --rm -v /var/folders/l0/lsgbf60d79x9cwhtvrq_blr80000gn/T/package.packageRoot224866318:/pkgsrc -v /var/folders/l0/lsgbf60d79x9cwhtvrq_blr80000gn/T/package.scriptRoot106928661:/pkgscripts -v /tmp/packaging-fpm-output207143536:/out kolide/fpm fpm -s dir -t deb -n launcher-launcher -v stable -p /out/launcher-stable.deb -C /pkgsrc --replaces launcher --conflicts launcher --after-install /pkgscripts/postinstall --before-remove /pkgscripts/prerm","level":"debug","msg":"Running fpm","span_id":"f9c3064eb58c01a2","trace_id":"a870da81a111e91f92ed131a205e8d6a","trace_is_sampled":false,"ts":"2019-10-25T17:07:47.885253Z"}
{"caller":"packagekit.PackageFPM","cmd":"docker run --rm -v /var/folders/l0/lsgbf60d79x9cwhtvrq_blr80000gn/T/package.packageRoot224866318:/pkgsrc -v /var/folders/l0/lsgbf60d79x9cwhtvrq_blr80000gn/T/package.scriptRoot106928661:/pkgscripts -v /tmp/packaging-fpm-output207143536:/out kolide/fpm fpm -s dir -t deb -n launcher-launcher -v stable -p /out/launcher-stable.deb -C /pkgsrc --replaces launcher --conflicts launcher --after-install /pkgscripts/postinstall --before-remove /pkgscripts/prerm","err":"exit status 125","level":"error","msg":"Error running fpm","span_id":"f9c3064eb58c01a2","stderr":"docker: Error response from daemon: Mounts denied: \r\nThe paths /var/folders/l0/lsgbf60d79x9cwhtvrq_blr80000gn/T/package.scriptRoot106928661 and /var/folders/l0/lsgbf60d79x9cwhtvrq_blr80000gn/T/package.packageRoot224866318\r\nare not shared from OS X and are not known to Docker.\r\nYou can configure shared paths from Docker -\u003e Preferences... -\u003e File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.\ntime=\"2019-10-25T12:07:48-05:00\" level=error msg=\"error waiting for container: context canceled\"\n","trace_id":"a870da81a111e91f92ed131a205e8d6a","trace_is_sampled":false,"ts":"2019-10-25T17:07:48.269742Z"}
could not generate packages: making package: packaging, target linux-systemd-deb: creating fpm package: docker: Error response from daemon: Mounts denied: 
The paths /var/folders/l0/lsgbf60d79x9cwhtvrq_blr80000gn/T/package.scriptRoot106928661 and /var/folders/l0/lsgbf60d79x9cwhtvrq_blr80000gn/T/package.packageRoot224866318
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
time="2019-10-25T12:07:48-05:00" level=error msg="error waiting for container: context canceled"
: exit status 125
```

**Comment by antoinette0x53** [comment]
Looks like the specific reasoning is here https://stackoverflow.com/questions/45122459/docker-mounts-denied-the-paths-are-not-shared-from-os-x-and-are-not-known/45123074

**Comment by directionless** [comment]
The `mounts denied` errors is common enough it's written up https://github.com/kolide/launcher/blob/master/docs/package-builder.md there's a pretty easy workaround. `export TMPDIR=/tmp`

Odd that the error was masked before.

I'm going to close this. Feel free to re-open if you still have issues
