### ISSUE TITLE
kolide_touchid_system_config table breaks on iMac Pro

### ISSUE THREAD

**Issue by FritzX6** [kolide/launcher#545]
#502 Appears to not be compatible with my iMac Pro

Hardware Details:
```
osquery> select * from system_info;
         cpu_brand = Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
   hardware_vendor = Apple Inc. 
    hardware_model = iMacPro1,1 
  hardware_version = 1.0 
```

OS details:
```
osquery> select * from os_version;
         name = Mac OS X
      version = 10.15
        major = 10
        minor = 15
        patch = 0
        build = 19A602
     platform = darwin
```

Osquery Details:

```
osquery> select * from osquery_info;
           pid = 90976
          uuid = E664D52B-5FBC-5A68-A0A5-24CAB9779442
   instance_id = 1f1fd415-174b-4723-ad48-5c62d06e4f11
       version = 3.3.0
   config_hash = 
  config_valid = 0
    extensions = active
build_platform = darwin
  build_distro = 10.12
    start_time = 1573843758
       watcher = -1
```

I attempted to query both tables today and was met with the following output:

✅**kolide_touchid_user_config**
```
osquery> select * from kolide_touchid_user_config WHERE uid = 502;
+-----+-------------------------+----------------+------------------+------------------+--------------------+
| uid | fingerprints_registered | touchid_unlock | touchid_applepay | effective_unlock | effective_applepay |
+-----+-------------------------+----------------+------------------+------------------+--------------------+
| 502 | 0                       | 0              | 0                | 0                | 0                  |
+-----+-------------------------+----------------+------------------+------------------+--------------------+
```
❗**kolide_touchid_system_config**
```
osquery> select * from kolide_touchid_system_config;
osquery> 2019/11/15 14:56:37 panic in processor: runtime error: index out of range [2] with length 2: goroutine 1384 [running]:
runtime/debug.Stack(0xc00017b930, 0x47f4400, 0xc000024420)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/apache/thrift/lib/go/thrift.(*TSimpleServer).processRequests.func1()
	/Users/fritz-imac/go/pkg/mod/github.com/apache/thrift@v0.12.0/lib/go/thrift/simple_server.go:198 +0x57
panic(0x47f4400, 0xc000024420)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
github.com/kolide/launcher/pkg/osquery/table.(*touchIDSystemConfigTable).generate(0xc0000c19c0, 0x49295e0, 0xc0000cc080, 0xc000434630, 0xc00041d350, 0x7, 0xc00041d338, 0x2, 0x8)
	/Users/fritz-imac/go/src/github.com/kolide/launcher/pkg/osquery/table/touchid_system_darwin.go:77 +0x76e
github.com/kolide/osquery-go/plugin/table.(*Plugin).Call(0xc000149320, 0x49295e0, 0xc0000cc080, 0xc000434390, 0xc0001512d8, 0xc0002d7c01, 0x432910b, 0xc0002d7c30)
	/Users/fritz-imac/go/pkg/mod/github.com/kolide/osquery-go@v0.0.0-20190904034940-a74aa860032d/plugin/table/table.go:68 +0x313
github.com/kolide/osquery-go.(*ExtensionManagerServer).Call(0xc000032080, 0x49295e0, 0xc0000cc080, 0xc00041d199, 0x5, 0xc00045a000, 0x1c, 0xc000434390, 0x0, 0x40147ce, ...)
	/Users/fritz-imac/go/pkg/mod/github.com/kolide/osquery-go@v0.0.0-20190904034940-a74aa860032d/server.go:241 +0x10f
github.com/kolide/osquery-go/gen/osquery.(*extensionProcessorCall).Process(0xc0001bcf40, 0x49295e0, 0xc0000cc080, 0x0, 0x49366c0, 0xc00042f7a0, 0x49366c0, 0xc00042f830, 0x4326fa8, 0x478cfe0, ...)
	/Users/fritz-imac/go/pkg/mod/github.com/kolide/osquery-go@v0.0.0-20190904034940-a74aa860032d/gen/osquery/osquery.go:1165 +0x2ec
github.com/kolide/osquery-go/gen/osquery.(*ExtensionProcessor).Process(0xc0000c1d40, 0x49295e0, 0xc0000cc080, 0x49366c0, 0xc00042f7a0, 0x49366c0, 0xc00042f830, 0x0, 0x0, 0x0)
	/Users/fritz-imac/go/pkg/mod/github.com/kolide/osquery-go@v0.0.0-20190904034940-a74aa860032d/gen/osquery/osquery.go:1084 +0x345
github.com/apache/thrift/lib/go/thrift.(*TSimpleServer).processRequests(0xc0000da980, 0x492d800, 0xc000434330, 0x0, 0x0)
	/Users/fritz-imac/go/pkg/mod/github.com/apache/thrift@v0.12.0/lib/go/thrift/simple_server.go:213 +0x292
github.com/apache/thrift/lib/go/thrift.(*TSimpleServer).innerAccept.func1(0xc0000da980, 0x492d800, 0xc000434330)
	/Users/fritz-imac/go/pkg/mod/github.com/apache/thrift@v0.12.0/lib/go/thrift/simple_server.go:143 +0x97
created by github.com/apache/thrift/lib/go/thrift.(*TSimpleServer).innerAccept
	/Users/fritz-imac/go/pkg/mod/github.com/apache/thrift@v0.12.0/lib/go/thrift/simple_server.go:141 +0x186
```

**Comment by jalseth** [comment]
@FritzX6 Please update with the output from `/usr/sbin/system_profiler SPiBridgeDataType` and `/usr/bin/bioutil -r -s` on this system and I will look into it.

**Comment by FritzX6** [comment]
Hey James! Sorry for the wait, the iMac Pro is in the office so I had to wait to get you the output:

```
➜  ~ /usr/sbin/system_profiler SPiBridgeDataType
Controller:

    Controller Information:

      Model Name: Apple T2 Security Chip
      Firmware Version: 17P1081
      Boot UUID: 8801E901-8089-449A-864C-836BB5F062E3
```


```
➜  ~ /usr/bin/bioutil -r -s
System Touch ID configuration:
Operation performed successfully.
```

**Comment by directionless** [comment]
There's some discussion that there is an underlying objective-c API for this.

* https://developer.apple.com/documentation/localauthentication/lacontext?language=objc
* https://developer.apple.com/documentation/localauthentication/lacontext/2867583-biometrytype?language=objc

**Comment by directionless** [comment]
I think this is fixed in https://github.com/kolide/launcher/pull/573
