### ISSUE TITLE
panic during launcher autoupdate

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#549]
Running in docker:

```
{"caller":"handler.go:84","msg":"Updated Binary ready to go","outputBinary":"/usr/local/kolide/bin/launcher-updates/1575340452/launcher","severity":"info","target":"linux/launcher-beta.tar.gz","ts":"2019-12-03T02:34:15.0471269Z"}
panic: close of closed channel

goroutine 31 [running]:
github.com/kolide/launcher/pkg/osquery/runtime.(*Runner).Shutdown(0xc000258ff0, 0x0, 0x0)
        /Users/seph/go/src/github.com/kolide/launcher/pkg/osquery/runtime/runtime.go:300 +0x3b
main.updateFinalizer.func1(0xc00064a060, 0xc0003322a0)
        /Users/seph/go/src/github.com/kolide/launcher/cmd/launcher/updater-finalizer.go:23 +0x4d
github.com/kolide/launcher/pkg/autoupdate.(*Updater).handler.func1(0xc000514aa0, 0x4e, 0x0, 0x0)
        /Users/seph/go/src/github.com/kolide/launcher/pkg/autoupdate/handler.go:90 +0x10df
github.com/kolide/updater/tuf.downloadAndNotify(0xc00010a0e0, 0xc000268280, 0x1a, 0xc00029c640, 0x33, 0xc000264970, 0x4, 0x4)
        /Users/seph/go/pkg/mod/github.com/kolide/updater@v0.0.0-20190315001611-15bbc19b5b80/tuf/client.go:316 +0x251
github.com/kolide/updater/tuf.(*autoupdater).update(0xc00025e200, 0xc00010a0e0)
        /Users/seph/go/pkg/mod/github.com/kolide/updater@v0.0.0-20190315001611-15bbc19b5b80/tuf/client.go:256 +0x115
github.com/kolide/updater/tuf.workerLoop(0xc0002624e0, 0xc000270360, 0xc0002703c0, 0xc0002804c8, 0xc00010a0e0, 0xc000270420, 0xc00025e200)
        /Users/seph/go/pkg/mod/github.com/kolide/updater@v0.0.0-20190315001611-15bbc19b5b80/tuf/client.go:288 +0x185
created by github.com/kolide/updater/tuf.NewClient
        /Users/seph/go/pkg/mod/github.com/kolide/updater@v0.0.0-20190315001611-15bbc19b5b80/tuf/client.go:160 +0x8ad
```

**Comment by directionless** [comment]
Probably a dup of https://github.com/kolide/launcher/issues/642
