### ISSUE TITLE
Flakey test github.com/kolide/launcher/pkg/osquery/tables/wmitable

### ISSUE THREAD

**Issue by James-Pickett** [kolide/launcher#815]
https://github.com/kolide/launcher/runs/6011731148?check_suite_focus=true

This test occasionally fails with this stack trace / error

This may have been introduced [by this](https://github.com/kolide/launcher/pull/803/files#diff-4ec28400e5a57bb2f51b72aaac11ba52ea11745b1f0dca469f1bd8c4093a5ae8), making the test parallel

```
Exception 0xc0000005 0x0 0x1f9c83a65b0 0x7ff85ac3b984
PC=0x7ff85ac3b984
signal arrived during external code execution

syscall.Syscall(0x7ff85aa7dd70, 0x1, 0xc000013bc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/runtime/syscall_windows.go:334 +0xe9
golang.org/x/sys/windows.(*Proc).Call(0xc00003cfa0, 0xc00028b900, 0x1, 0x1, 0x501a65, 0x0, 0xc00028b900, 0xc0002b12a8)
	C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.0.0-20211025201205-69cdffdb9359/windows/dll_windows.go:170 +0x1db
golang.org/x/sys/windows.(*LazyProc).Call(0xc00014d2c0, 0xc00028b900, 0x1, 0x1, 0x7eeaeb, 0x7ff85a9fe8f0, 0x1, 0x1f9c838ccf8)
	C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.0.0-20211025201205-69cdffdb9359/windows/dll_windows.go:348 +0xa8
github.com/go-ole/go-ole.VariantClear(0xc000013bc0, 0x8b3ed8, 0xc000031828)
	C:/Users/runneradmin/go/pkg/mod/github.com/go-ole/go-ole@v1.2.6/com.go:248 +0xb9
github.com/go-ole/go-ole.(*VARIANT).Clear(0xc000013bc0, 0x0, 0xc0002a4a80)
	C:/Users/runneradmin/go/pkg/mod/github.com/go-ole/go-ole@v1.2.6/variant.go:47 +0x45
github.com/kolide/launcher/pkg/wmi.Query(0x9475a0, 0xc00015d830, 0x8a218c, 0x15, 0xc00003d760, 0x2, 0x2, 0xc0002b1b28, 0x3, 0x3, ...)
	D:/a/launcher/launcher/pkg/wmi/wmi.go:179 +0xd16
github.com/kolide/launcher/pkg/osquery/tables/wmitable.(*Table).generate(0xc0000046a8, 0x947530, 0xc000014118, 0xc00015d800, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/a/launcher/launcher/pkg/osquery/tables/wmitable/wmitable.go:101 +0xd45
github.com/kolide/launcher/pkg/osquery/tables/wmitable.TestQueries.func1(0xc000031680)
	D:/a/launcher/launcher/pkg/osquery/tables/wmitable/wmitable_test.go:125 +0x4fc
testing.tRunner(0xc000031680, 0xc000050240)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1203 +0x203
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 1 [chan receive]:
testing.tRunner.func1(0xc000031080)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1169 +0x3c6
testing.tRunner(0xc000031080, 0xc0001dfc78)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
testing.runTests(0xc000004690, 0xabeec0, 0x1, 0x1, 0xc08ddf91858f744c, 0x8bb3a82035, 0xacaf00, 0xc000048088)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1519 +0x613
testing.(*M).Run(0xc000090180, 0x0)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1427 +0x3b4
main.main()
	_testmain.go:91 +0x357

goroutine 6 [chan receive]:
testing.tRunner.func1(0xc000031200)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1169 +0x3c6
testing.tRunner(0xc000031200, 0x8b3f08)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 7 [chan receive]:
testing.runTests.func1.1(0xc000031080)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1526 +0x67
created by testing.runTests.func1
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1526 +0xe7

goroutine 9 [chan send]:
testing.tRunner.func1.1(0xc0001e3d7f, 0x0, 0x0, 0xc000031980, 0x1)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1133 +0x98
testing.tRunner.func1(0xc000031980)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1194 +0x560
testing.tRunner(0xc000031980, 0xc0000502d0)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 10 [chan send]:
testing.tRunner.func1.1(0xc000295d7f, 0x0, 0x0, 0xc000031c80, 0x1)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1133 +0x98
testing.tRunner.func1(0xc000031c80)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1194 +0x560
testing.tRunner(0xc000031c80, 0xc000050360)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 11 [chan send]:
testing.tRunner.func1.1(0xc000259d7f, 0x0, 0x0, 0xc00015e000, 0x1)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1133 +0x98
testing.tRunner.func1(0xc00015e000)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1194 +0x560
testing.tRunner(0xc00015e000, 0xc0000503f0)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 12 [syscall, locked to thread]:
syscall.Syscall6(0x7ff85a9fe5f0, 0x6, 0x1f9c83687b8, 0xc000014cf0, 0xc000216aa8, 0x1, 0x409, 0xc00027a858, 0x0, 0x0, ...)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/runtime/syscall_windows.go:347 +0xf2
github.com/go-ole/go-ole.getIDsOfName(0x1f9c83687b8, 0xc00025cf70, 0x1, 0x1, 0xc00027a858, 0x1, 0x1, 0x0, 0x0)
	C:/Users/runneradmin/go/pkg/mod/github.com/go-ole/go-ole@v1.2.6/idispatch_windows.go:19 +0x2f0
github.com/go-ole/go-ole.(*IDispatch).GetIDsOfName(...)
	C:/Users/runneradmin/go/pkg/mod/github.com/go-ole/go-ole@v1.2.6/idispatch.go:22
github.com/go-ole/go-ole.(*IDispatch).GetSingleIDOfName(0x1f9c83687b8, 0x201800004, 0x0, 0x0, 0x0, 0xc00025cff0)
	C:/Users/runneradmin/go/pkg/mod/github.com/go-ole/go-ole@v1.2.6/idispatch.go:47 +0x88
github.com/go-ole/go-ole.(*IDispatch).Invoke(...)
	C:/Users/runneradmin/go/pkg/mod/github.com/go-ole/go-ole@v1.2.6/idispatch.go:27
github.com/go-ole/go-ole.(*IDispatch).InvokeWithOptionalArgs(0x1f9c83687b8, 0x8ad2d5, 0x6, 0x2, 0x0, 0x0, 0x0, 0xc000276f30, 0x0, 0x0)
	C:/Users/runneradmin/go/pkg/mod/github.com/go-ole/go-ole@v1.2.6/idispatch.go:69 +0xbb
github.com/go-ole/go-ole/oleutil.GetProperty(...)
	C:/Users/runneradmin/go/pkg/mod/github.com/go-ole/go-ole@v1.2.6/oleutil/oleutil.go:65
github.com/kolide/launcher/pkg/wmi.(*oleHandler).HandleVariant(0xc000232340, 0xc00021a2b8, 0x0, 0x0)
	D:/a/launcher/launcher/pkg/wmi/wmi.go:203 +0x18c
github.com/go-ole/go-ole/oleutil.ForEach(0x1f9c838cac8, 0xc00025d700, 0x0, 0x0)
	C:/Users/runneradmin/go/pkg/mod/github.com/go-ole/go-ole@v1.2.6/oleutil/oleutil.go:122 +0x329
github.com/kolide/launcher/pkg/wmi.Query(0x9475a0, 0xc000222ab0, 0x89e54a, 0xd, 0xc000224a20, 0x6, 0x6, 0xc00025db28, 0x3, 0x3, ...)
	D:/a/launcher/launcher/pkg/wmi/wmi.go:175 +0xc46
github.com/kolide/launcher/pkg/osquery/tables/wmitable.(*Table).generate(0xc0000046a8, 0x947530, 0xc000014118, 0xc000222a80, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/a/launcher/launcher/pkg/osquery/tables/wmitable/wmitable.go:101 +0xd45
github.com/kolide/launcher/pkg/osquery/tables/wmitable.TestQueries.func1(0xc00015e300)
	D:/a/launcher/launcher/pkg/osquery/tables/wmitable/wmitable_test.go:125 +0x4fc
testing.tRunner(0xc00015e300, 0xc000050480)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1203 +0x203
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 13 [chan send]:
testing.tRunner.func1.1(0xc000251d7f, 0x0, 0x0, 0xc00015e600, 0x1)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1133 +0x98
testing.tRunner.func1(0xc00015e600)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1194 +0x560
testing.tRunner(0xc00015e600, 0xc000050510)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 14 [chan send]:
testing.tRunner.func1.1(0xc000255d7f, 0x0, 0x0, 0xc00015e900, 0x1)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1133 +0x98
testing.tRunner.func1(0xc00015e900)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1194 +0x560
testing.tRunner(0xc00015e900, 0xc0000505a0)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 15 [chan send]:
testing.tRunner.func1.1(0xc000283d7f, 0x0, 0x0, 0xc00015ec00, 0x1)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1133 +0x98
testing.tRunner.func1(0xc00015ec00)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1194 +0x560
testing.tRunner(0xc00015ec00, 0xc000050630)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 16 [chan send]:
testing.tRunner.func1.1(0xc000287d7f, 0x0, 0x0, 0xc00015ef00, 0x1)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1133 +0x98
testing.tRunner.func1(0xc00015ef00)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1194 +0x560
testing.tRunner(0xc00015ef00, 0xc0000506c0)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 18 [chan send]:
testing.tRunner.func1.1(0xc000291d7f, 0x0, 0x0, 0xc00015f200, 0x1)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1133 +0x98
testing.tRunner.func1(0xc00015f200)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1194 +0x560
testing.tRunner(0xc00015f200, 0xc000050750)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 19 [chan send]:
testing.tRunner.func1.1(0xc00020fd7f, 0x0, 0x0, 0xc00015f500, 0x1)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1133 +0x98
testing.tRunner.func1(0xc00015f500)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1194 +0x560
testing.tRunner(0xc00015f500, 0xc0000507e0)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 20 [chan send]:
testing.tRunner.func1.1(0xc00020bd7f, 0x0, 0x0, 0xc00015f800, 0x1)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1133 +0x98
testing.tRunner.func1(0xc00015f800)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1194 +0x560
testing.tRunner(0xc00015f800, 0xc000050870)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1207 +0x22b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/testing/testing.go:1248 +0x5d8

goroutine 21 [sync.Cond.Wait, locked to thread]:
sync.runtime_notifyListWait(0xc000048208, 0x0)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/runtime/sema.go:513 +0x117
sync.(*Cond).Wait(0xc0000481f8)
	C:/hostedtoolcache/windows/go/1.16.15/x64/src/sync/cond.go:56 +0x99
github.com/scjalliance/comshim.(*Shim).run.func1(0xc000018f60, 0xc0000481e0)
	C:/Users/runneradmin/go/pkg/mod/github.com/scjalliance/comshim@v0.0.0-20190308082608-cf06d2532c4e/shim.go:118 +0xef
created by github.com/scjalliance/comshim.(*Shim).run
	C:/Users/runneradmin/go/pkg/mod/github.com/scjalliance/comshim@v0.0.0-20190308082608-cf06d2532c4e/shim.go:89 +0x7b
rax     0x7ff85ac3b980
rbx     0x1f9c838ccf8
rcx     0x1f9c83a65b0
rdi     0xc000013bc0
rsi     0x0
rbp     0x9
rsp     0xbc58dffc68
r8      0x0
r9      0x0
r10     0xbaac1f10365eb170
r11     0xbc58dffd08
r12     0x2000
r13     0x1000ff7ffc
r14     0x0
r15     0x6000
rip     0x7ff85ac3b984
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
FAIL	github.com/kolide/launcher/pkg/osquery/tables/wmitable	0.854s
ok  	github.com/kolide/launcher/pkg/osquery/tables/zfs	1.054s	coverage: 33.3% of statements
ok  	github.com/kolide/launcher/pkg/packagekit	1.059s	coverage: 13.3% of statements
ok  	github.com/kolide/launcher/pkg/packagekit/applenotarization	1.152s	coverage: 71.2% of statements
ok  	github.com/kolide/launcher/pkg/packagekit/authenticode	1.045s	coverage: 0.0% of statements
ok  	github.com/kolide/launcher/pkg/packagekit/wix	1.053s	coverage: 23.4% of statements
ok  	github.com/kolide/launcher/pkg/packaging	2.153s	coverage: 32.5% of statements
?   	github.com/kolide/launcher/pkg/pb/launcher	[no test files]
?   	github.com/kolide/launcher/pkg/pb/querytarget	[no test files]
?   	github.com/kolide/launcher/pkg/ptycmd	[no test files]
?   	github.com/kolide/launcher/pkg/querytarget	[no test files]
ok  	github.com/kolide/launcher/pkg/service	13.891s	coverage: 22.5% of statements
?   	github.com/kolide/launcher/pkg/service/mock	[no test files]
ok  	github.com/kolide/launcher/pkg/simulator	1.053s	coverage: 25.9% of statements
?   	github.com/kolide/launcher/pkg/windows/oleconv	[no test files]
?   	github.com/kolide/launcher/pkg/windows/windowsupdate	[no test files]
ok  	github.com/kolide/launcher/pkg/wmi	1.627s	coverage: 87.5% of statements
?   	github.com/kolide/launcher/pkg/wsrelay	[no test files]
?   	github.com/kolide/launcher/tools	[no test files]
?   	github.com/kolide/launcher/tools/autoupdate-v1-tests	[no test files]
FAIL
mingw32-make: *** [Makefile:211: test] Error 1
Error: Process completed with exit code 1.
```

**Comment by directionless** [comment]
Interesting. I suspect you're right that the parallel tests unearthed this. I don't remember seeing it before. Though there's something vaguely familiar about it.
